# Source: kyverno-policies/templates/require-non-root-user.yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-non-root-user
  annotations:
    policies.kyverno.io/title: Reqire Non-root User
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Following the least privilege principle, containers should not be run as root. This policy ensures containers either have `runAsNonRoot` set to `true` or `runAsUser` > 0.
  labels:
    app.kubernetes.io/name: kyverno-policies
    helm.sh/chart: kyverno-policies-1.0.1-bb.7
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.1-bb.7"
    app.kubernetes.io/component: policy
    app.kubernetes.io/part-of: kyverno
    app: kyverno
spec:
  webhookTimeoutSeconds: 30
  validationFailureAction: enforce
  rules:
  - name: non-root-user
    exclude:
      any:
      - resources:
          names:
          - kyverno-policies-script-test*
          namespaces:
          - kyverno-policies
    match:
      all:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
    validate:
      message: >-
        Either `runAsNonRoot` must be set to true or `runAsUser` must be > 0 in spec.securityContext or (spec.containers[*].securityContext, spec.initContainers[*].securityContext, and spec.ephemeralContainers[*].securityContext)
      anyPattern:
      - spec:
          securityContext:
            runAsUser: '>0'
          containers:
          - (securityContext):
              (runAsUser): '>0'
          =(initContainers):
          - (securityContext):
              (runAsUser): 0
            name: "istio-foo | istio-init | not-me"
          =(ephemeralContainers):
          - (securityContext):
              (runAsUser): '>0'
      - spec:
          containers:
          - securityContext:
              runAsUser: 0
            name: "istio-foo | istio-init | not-me"
          =(initContainers):
          - (securityContext):
              runAsUser: '>0'
          =(ephemeralContainers):
          - (securityContext):
              runAsUser: '>0'
      - spec:
          containers:
          - securityContext:
              runAsUser: '>0'
          =(initContainers):
          - (securityContext):
              runAsUser: 0
            name: "istio-foo | istio-init | not-me"
          =(ephemeralContainers):
          - (securityContext):
              runAsUser: 0
            name: "istio-foo | istio-init | not-me"
      - spec:
          containers:
          - securityContext:
              runAsNonRoot: false
            name: "istio-foo | istio-init | not-me"
          =(initContainers):
          - (securityContext):
              runAsNonRoot: true
          =(ephemeralContainers):
          - (securityContext):
              runAsNonRoot: true
      - spec:
          containers:
          - securityContext:
              runAsNonRoot: true
          =(initContainers):
          - (securityContext):
              runAsNonRoot: false
            name: "istio-foo | istio-init | not-me"
          =(ephemeralContainers):
          - (securityContext):
              runAsNonRoot: false
            name: "istio-foo | istio-init | not-me"
      - spec:
          securityContext:
            runAsNonRoot: true
          containers:
          - =(securityContext):
              =(runAsNonRoot): true
            (name): "!istio-foo & !istio-init & !not-me"
          =(initContainers):
          - =(securityContext):
              =(runAsNonRoot): true
            (name): "!istio-foo & !istio-init & !not-me"
          =(ephemeralContainers):
          - =(securityContext):
              =(runAsNonRoot): true
            (name): "!istio-foo & !istio-init & !not-me"
      - spec:
          securityContext:
            runAsUser: ">0"
          containers:
          - =(securityContext):
              =(runAsUser): ">0"
            (name): "!istio-foo & !istio-init & !not-me"
          =(initContainers):
          - =(securityContext):
              =(runAsUser): ">0"
            (name): "!istio-foo & !istio-init & !not-me"
          =(ephemeralContainers):
          - =(securityContext):
              =(runAsUser): ">0"
            (name): "!istio-foo & !istio-init & !not-me"
      - spec:
          containers:
          - securityContext:
              runAsNonRoot: true
            (name): "!istio-foo & !istio-init & !not-me"
          =(initContainers):
          - securityContext:
              runAsNonRoot: true
            (name): "!istio-foo & !istio-init & !not-me"
          =(ephemeralContainers):
          - securityContext:
              runAsNonRoot: true
            (name): "!istio-foo & !istio-init & !not-me"
      - spec:
          containers:
          - securityContext:
              runAsUser: ">0"
            (name): "!istio-foo & !istio-init & !not-me"
          =(initContainers):
          - securityContext:
              runAsNonRoot: true
            (name): "!istio-foo & !istio-init & !not-me"
          =(ephemeralContainers):
          - securityContext:
              runAsNonRoot: true
            (name): "!istio-foo & !istio-init & !not-me"
      - spec:
          containers:
          - securityContext:
              runAsNonRoot: true
            (name): "!istio-foo & !istio-init & !not-me"
          =(initContainers):
          - securityContext:
              runAsUser: ">0"
            (name): "!istio-foo & !istio-init & !not-me"
          =(ephemeralContainers):
          - securityContext:
              runAsNonRoot: true
            (name): "!istio-foo & !istio-init & !not-me"
      - spec:
          containers:
          - securityContext:
              runAsUser: ">0"
            (name): "!istio-foo & !istio-init & !not-me"
          =(initContainers):
          - securityContext:
              runAsUser: ">0"
            (name): "!istio-foo & !istio-init & !not-me"
          =(ephemeralContainers):
          - securityContext:
              runAsNonRoot: true
            (name): "!istio-foo & !istio-init & !not-me"
      - spec:
          containers:
          - securityContext:
              runAsNonRoot: true
            (name): "!istio-foo & !istio-init & !not-me"
          =(initContainers):
          - securityContext:
              runAsNonRoot: true
            (name): "!istio-foo & !istio-init & !not-me"
          =(ephemeralContainers):
          - securityContext:
              runAsUser: ">0"
            (name): "!istio-foo & !istio-init & !not-me"
      - spec:
          containers:
          - securityContext:
              runAsUser: ">0"
            (name): "!istio-foo & !istio-init & !not-me"
          =(initContainers):
          - securityContext:
              runAsNonRoot: true
            (name): "!istio-foo & !istio-init & !not-me"
          =(ephemeralContainers):
          - securityContext:
              runAsUser: ">0"
            (name): "!istio-foo & !istio-init & !not-me"
      - spec:
          containers:
          - securityContext:
              runAsNonRoot: true
            (name): "!istio-foo & !istio-init & !not-me"
          =(initContainers):
          - securityContext:
              runAsUser: ">0"
            (name): "!istio-foo & !istio-init & !not-me"
          =(ephemeralContainers):
          - securityContext:
              runAsUser: ">0"
            (name): "!istio-foo & !istio-init & !not-me"
      - spec:
          containers:
          - securityContext:
              runAsUser: ">0"
            (name): "!istio-foo & !istio-init & !not-me"
          =(initContainers):
          - securityContext:
              runAsUser: ">0"
            (name): "!istio-foo & !istio-init & !not-me"
          =(ephemeralContainers):
          - securityContext:
              runAsUser: ">0"
            (name): "!istio-foo & !istio-init & !not-me"
