apiVersion: v1
kind: Pod
metadata:
  name: basic-run-as-fail
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: c1
    image: nginx
    args: ["sleep", "infinity"]
  initContainers:
  - name: c1
    image: nginx
    securityContext:
      runAsNonRoot: false
---
apiVersion: v1
kind: Pod
metadata:
  name: basic-run-as-pass
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: c1
    image: nginx
    args: ["sleep", "infinity"]
  initContainers:
  - name: c1
    image: nginx
    securityContext:
      runAsNonRoot: true
---
apiVersion: v1
kind: Pod
metadata:
  name: basic-run-as-user-fail
spec:
  securityContext:
    runAsUser: 1001
  containers:
  - name: c1
    image: nginx
    args: ["sleep", "infinity"]
  initContainers:
  - name: c1
    image: nginx
    securityContext:
      runAsUser: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: basic-run-as-user-pass
spec:
  securityContext:
    runAsUser: 1001
  containers:
  - name: c1
    image: nginx
    args: ["sleep", "infinity"]
  initContainers:
  - name: c1
    image: nginx
    securityContext:
      runAsUser: 1001