apiVersion: v1
kind: Pod
metadata:
  name: require-non-root-user-istio-init-exception
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: c1
    image: nginx
    args: ["sleep", "infinity"]
  initContainers:
  - name: istio-init
    image: nginx
    securityContext:
      runAsNonRoot: true
  - name: c1
    image: nginx
    securityContext:
      runAsNonRoot: true
---
apiVersion: v1
kind: Pod
metadata:
  name: require-non-root-user-istio-init-exception-omitted
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: c1
    image: nginx
    args: ["sleep", "infinity"]
  initContainers:
  - name: istio-init
    image: nginx
  - name: c1
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: require-non-root-user-istio-init-exception-fail
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: c1
    image: nginx
    args: ["sleep", "infinity"]
  initContainers:
  - name: istio-init
    image: nginx
    securityContext:
      runAsNonRoot: false
  - name: c1
    image: nginx
    securityContext:
      runAsNonRoot: false