apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kiali
  name: kiali-7fc5c8cc98-hnn66-run-as
spec:
  containers:
  - name: kiali
    image: registry1.dso.mil/ironbank/opensource/kiali/kiali:v1.58.0
    resources:
      limits:
        cpu: 200m
        memory: 368Mi
      requests:
        cpu: 200m
        memory: 368Mi
    securityContext:
      runAsUser: 1001
  initContainers:
  - name: istio-init
    image: registry1.dso.mil/ironbank/opensource/istio/proxyv2:1.15.0
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 0
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kiali
  name: kiali-container-run-as
spec:
  containers:
  - name: istio-init
    image: registry1.dso.mil/ironbank/opensource/kiali/kiali:v1.58.0
    resources:
      limits:
        cpu: 200m
        memory: 368Mi
      requests:
        cpu: 200m
        memory: 368Mi
    securityContext:
      runAsUser: 0
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kiali
  name: kiali-container-fail-run-as
spec:
  containers:
  - name: istio-init
    image: registry1.dso.mil/ironbank/opensource/kiali/kiali:v1.58.0
    resources:
      limits:
        cpu: 200m
        memory: 368Mi
      requests:
        cpu: 200m
        memory: 368Mi
    securityContext:
      runAsUser: 0
  initContainers:
  - name: fail
    image: registry1.dso.mil/ironbank/opensource/istio/proxyv2:1.15.0
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 0