apiVersion: v1
kind: Pod
metadata:
  name: basic-omit-run-as-fail
spec:
  containers:
  - name: c1
    image: nginx
    args: ["sleep", "infinity"]
  initContainers:
  - name: c1
    image: nginx
    securityContext:
      runAsNonRoot: false
---
apiVersion: v1
kind: Pod
metadata:
  name: basic-omit-run-as-pass
spec:
  containers:
  - name: c1
    image: nginx
    args: ["sleep", "infinity"]
    securityContext:
      runAsNonRoot: true
  initContainers:
  - name: c1
    image: nginx
    securityContext:
      runAsNonRoot: true
---
apiVersion: v1
kind: Pod
metadata:
  name: basic-omit-run-as-user-fail
spec:
  containers:
  - name: c1
    image: nginx
    args: ["sleep", "infinity"]
  initContainers:
  - name: c1
    image: nginx
    securityContext:
      runAsUser: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: basic-omit-run-as-user-pass
spec:
  containers:
  - name: c1
    image: nginx
    args: ["sleep", "infinity"]
    securityContext:
      runAsUser: 1001
  initContainers:
  - name: c1
    image: nginx
    securityContext:
      runAsUser: 1001